# Generated by Django 3.1.2 on 2020-12-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='main_img',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
